### ISSUE TITLE
Error "While parsing a block mapping, did not find expected key."

### ISSUE THREAD

**Issue by tocalvo** [muhamedzeema/appgallery-deply-action#1]
Hi! 👋 

We are going to release our app to the Huawei app gallery, and found this action, so looks perfect!
But looks like is giving us this error:

`
Download action repository 'muhamedzeema/appgallery-deply-action@v1'
Error: muhamedzeema/appgallery-deply-action/v1/action.yml:
Error: muhamedzeema/appgallery-deply-action/v1/action.yml: (Line: 7, Col: 19, Idx: 180) - (Line: 8, Col: 13, Idx: 203): While parsing a block mapping, did not find expected key.
Error: System.ArgumentException: Unexpected type '' encountered while reading 'action manifest root'. The type 'MappingToken' was expected.
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
Error: Fail to load muhamedzeema/appgallery-deply-action/v1/action.yml
`

We add the action using the example:

`  - name: Deploy to Huawei App Gallery
        uses: muhamedzeema/appgallery-deply-action@v1
        with:
          client-id: ${{secrets.HUAWEI_CLIENT_ID}}
          client-key: ${{secrets.HUAWEI_CLIENT_KEY}}
          app-id: ${{secrets.HUAWEI_APP_ID}}
          file-extension: "aab"
          file-path: "./apps/pepephone/android/app/build/outputs/bundle/release/app-release.aab"
`

Secrets are added but i cant find the error :(

**Comment by muhamedzeema** [comment]
@tocalvo Hi, 
please try use uses: muhamedzeema/appgallery-deply-action@main instead of v1

**Comment by tocalvo** [comment]
Thanks you so much! Works nice now 😄 .
Ok, nice nice not because is giving us "Error: [cds]add apk failed, additional msg is [package name already exists]" but looks like something wrong in our side 😅 , not in the action.

Thanks you so much again for the fast response!

**Comment by muhamedzeema** [comment]
@tocalvo Hello,
i think its from my side, i forgot and added .apk for the filename by default. i will revisit it today and will let your know ✌️
 [https://github.com/muhamedzeema/appgallery-deply-action/blob/e98161d95c53efb3188f4b6746136ff772515235/index.js#L109](https://github.com/muhamedzeema/appgallery-deply-action/blob/e98161d95c53efb3188f4b6746136ff772515235/index.js#L109)
