### ISSUE TITLE
Action is always publishing the app even with submit set to false

### ISSUE THREAD

**Issue by dinisnunes1** [muhamedzeema/appgallery-deply-action#6]
**Problem:**
Action is always publishing the app even with `submit` set to `false`. I can check the logs and see the `successfully submitted 🎉🎉🎉🎉🎉🎉` message if I set submit to `false` or `true`. 

**Solution:**
Validate which type the `submit` input type really is, because the if condition `if (submit) {}` is always being executed.

**Some Tests:**
After some tests and reading the docs, the `input` type will collect the `submit` option as string (and not `boolean` as it is described in the [readme file](https://github.com/muhamedzeema/appgallery-deply-action/blob/main/README.md?plain=1#L38)). So the if condition `if(submit){}` is always being executed.

A quick test doing a `console.log(typeof submit)` returned `string`. So the solution is to replace the if condition here https://github.com/muhamedzeema/appgallery-deply-action/blob/main/index.js#L190 with: 
```
if(submit === 'true'){
   //submit code here
}
```

**Comment by dinisnunes1** [comment]
@muhamedzeema I will open a PR with a fix

**Comment by muhamedzeema** [comment]
merged, thank you @dinisnunes1
